export type CountryData = {
  country: string, currency: string, code: string
}

const countriesData: CountryData[] = [
  { country: "United Arab Emirates", currency: "Dirham", code: "AED" },
  { country: "Afghanistan", currency: "Afghani", code: "AFN" },
  { country: "Albania", currency: "Lek", code: "ALL" },
  { country: "Armenia", currency: "Dram", code: "AMD" },
  { country: "Netherlands Antilles", currency: "Guilder", code: "ANG" },
  { country: "Angola", currency: "Kwanza", code: "AOA" },
  { country: "Argentina", currency: "Peso", code: "ARS" },
  { country: "Australia", currency: "Dollar", code: "AUD" },
  { country: "Aruba", currency: "Florin", code: "AWG" },
  { country: "Azerbaijan", currency: "Manat", code: "AZN" },
  { country: "Bosnia and Herzegovina", currency: "Convertible Mark", code: "BAM" },
  { country: "Barbados", currency: "Dollar", code: "BBD" },
  { country: "Bangladesh", currency: "Taka", code: "BDT" },
  { country: "Bulgaria", currency: "Lev", code: "BGN" },
  { country: "Bahrain", currency: "Dinar", code: "BHD" },
  { country: "Burundi", currency: "Franc", code: "BIF" },
  { country: "Bermuda", currency: "Dollar", code: "BMD" },
  { country: "Brunei", currency: "Dollar", code: "BND" },
  { country: "Bolivia", currency: "Boliviano", code: "BOB" },
  { country: "Brazil", currency: "Real", code: "BRL" },
  { country: "Bahamas", currency: "Dollar", code: "BSD" },
  { country: "Bhutan", currency: "Ngultrum", code: "BTN" },
  { country: "Botswana", currency: "Pula", code: "BWP" },
  { country: "Belarus", currency: "Ruble", code: "BYN" },
  { country: "Belize", currency: "Dollar", code: "BZD" },
  { country: "Canada", currency: "Dollar", code: "CAD" },
  { country: "Democratic Republic of Congo", currency: "Franc", code: "CDF" },
  { country: "Switzerland", currency: "Franc", code: "CHF" },
  { country: "Chile", currency: "Unidad de Fomento", code: "CLF" },
  { country: "Chile", currency: "Peso", code: "CLP" },
  { country: "China (offshore)", currency: "Yuan Renminbi", code: "CNH" },
  { country: "China", currency: "Yuan Renminbi", code: "CNY" },
  { country: "Colombia", currency: "Peso", code: "COP" },
  { country: "Costa Rica", currency: "Colon", code: "CRC" },
  { country: "Cuba", currency: "Peso", code: "CUP" },
  { country: "Cape Verde", currency: "Escudo", code: "CVE" },
  { country: "Czech Republic", currency: "Koruna", code: "CZK" },
  { country: "Djibouti", currency: "Franc", code: "DJF" },
  { country: "Denmark", currency: "Krone", code: "DKK" },
  { country: "Dominican Republic", currency: "Peso", code: "DOP" },
  { country: "Algeria", currency: "Dinar", code: "DZD" },
  { country: "Egypt", currency: "Pound", code: "EGP" },
  { country: "Eritrea", currency: "Nakfa", code: "ERN" },
  { country: "Ethiopia", currency: "Birr", code: "ETB" },
  { country: "Eurozone", currency: "Euro", code: "EUR" },
  { country: "Fiji", currency: "Dollar", code: "FJD" },
  { country: "Falkland Islands", currency: "Pound", code: "FKP" },
  { country: "Faroe Islands", currency: "Krone", code: "FOK" },
  { country: "United Kingdom", currency: "Pound Sterling", code: "GBP" },
  { country: "Georgia", currency: "Lari", code: "GEL" },
  { country: "Guernsey", currency: "Pound", code: "GGP" },
  { country: "Ghana", currency: "Cedi", code: "GHS" },
  { country: "Gibraltar", currency: "Pound", code: "GIP" },
  { country: "Gambia", currency: "Dalasi", code: "GMD" },
  { country: "Guinea", currency: "Franc", code: "GNF" },
  { country: "Guatemala", currency: "Quetzal", code: "GTQ" },
  { country: "Guyana", currency: "Dollar", code: "GYD" },
  { country: "Hong Kong", currency: "Dollar", code: "HKD" },
  { country: "Honduras", currency: "Lempira", code: "HNL" },
  { country: "Croatia", currency: "Kuna", code: "HRK" },
  { country: "Haiti", currency: "Gourde", code: "HTG" },
  { country: "Hungary", currency: "Forint", code: "HUF" },
  { country: "Indonesia", currency: "Rupiah", code: "IDR" },
  { country: "Israel", currency: "Shekel", code: "ILS" },
  { country: "Isle of Man", currency: "Pound", code: "IMP" },
  { country: "India", currency: "Rupee", code: "INR" },
  { country: "Iraq", currency: "Dinar", code: "IQD" },
  { country: "Iran", currency: "Rial", code: "IRR" },
  { country: "Iceland", currency: "Krona", code: "ISK" },
  { country: "Jersey", currency: "Pound", code: "JEP" },
  { country: "Jamaica", currency: "Dollar", code: "JMD" },
  { country: "Jordan", currency: "Dinar", code: "JOD" },
  { country: "Japan", currency: "Yen", code: "JPY" },
  { country: "Kenya", currency: "Shilling", code: "KES" },
  { country: "Kyrgyzstan", currency: "Som", code: "KGS" },
  { country: "Cambodia", currency: "Riel", code: "KHR" },
  { country: "Kiribati", currency: "Dollar", code: "KID" },
  { country: "Comoros", currency: "Franc", code: "KMF" },
  { country: "South Korea", currency: "Won", code: "KRW" },
  { country: "Kuwait", currency: "Dinar", code: "KWD" },
  { country: "Cayman Islands", currency: "Dollar", code: "KYD" },
  { country: "Kazakhstan", currency: "Tenge", code: "KZT" },
  { country: "Laos", currency: "Kip", code: "LAK" },
  { country: "Lebanon", currency: "Pound", code: "LBP" },
  { country: "Sri Lanka", currency: "Rupee", code: "LKR" },
  { country: "Liberia", currency: "Dollar", code: "LRD" },
  { country: "Lesotho", currency: "Loti", code: "LSL" },
  { country: "Libya", currency: "Dinar", code: "LYD" },
  { country: "Morocco", currency: "Dirham", code: "MAD" },
  { country: "Moldova", currency: "Leu", code: "MDL" },
  { country: "Madagascar", currency: "Ariary", code: "MGA" },
  { country: "North Macedonia", currency: "Denar", code: "MKD" },
  { country: "Myanmar", currency: "Kyat", code: "MMK" },
  { country: "Mongolia", currency: "Tugrik", code: "MNT" },
  { country: "Macau", currency: "Pataca", code: "MOP" },
  { country: "Mauritania", currency: "Ouguiya", code: "MRU" },
  { country: "Mauritius", currency: "Rupee", code: "MUR" },
  { country: "Maldives", currency: "Rufiyaa", code: "MVR" },
  { country: "Malawi", currency: "Kwacha", code: "MWK" },
  { country: "Mexico", currency: "Peso", code: "MXN" },
  { country: "Malaysia", currency: "Ringgit", code: "MYR" },
  { country: "Mozambique", currency: "Metical", code: "MZN" },
  { country: "Namibia", currency: "Dollar", code: "NAD" },
  { country: "Nigeria", currency: "Naira", code: "NGN" },
  { country: "Nicaragua", currency: "Cordoba", code: "NIO" },
  { country: "Norway", currency: "Krone", code: "NOK" },
  { country: "Nepal", currency: "Rupee", code: "NPR" },
  { country: "New Zealand", currency: "Dollar", code: "NZD" },
  { country: "Oman", currency: "Rial", code: "OMR" },
  { country: "Panama", currency: "Balboa", code: "PAB" },
  { country: "Peru", currency: "Sol", code: "PEN" },
  { country: "Papua New Guinea", currency: "Kina", code: "PGK" },
  { country: "Philippines", currency: "Peso", code: "PHP" },
  { country: "Pakistan", currency: "Rupee", code: "PKR" },
  { country: "Poland", currency: "Zloty", code: "PLN" },
  { country: "Paraguay", currency: "Guarani", code: "PYG" },
  { country: "Qatar", currency: "Riyal", code: "QAR" },
  { country: "Romania", currency: "Leu", code: "RON" },
  { country: "Serbia", currency: "Dinar", code: "RSD" },
  { country: "Russia", currency: "Ruble", code: "RUB" },
  { country: "Rwanda", currency: "Franc", code: "RWF" },
  { country: "Saudi Arabia", currency: "Riyal", code: "SAR" },
  { country: "Solomon Islands", currency: "Dollar", code: "SBD" },
  { country: "Seychelles", currency: "Rupee", code: "SCR" },
  { country: "Sudan", currency: "Pound", code: "SDG" },
  { country: "Sweden", currency: "Krona", code: "SEK" },
  { country: "Singapore", currency: "Dollar", code: "SGD" },
  { country: "Saint Helena", currency: "Pound", code: "SHP" },
  { country: "Sierra Leone", currency: "Leone", code: "SLE" },
  { country: "Sierra Leone", currency: "Leone (old)", code: "SLL" },
  { country: "Somalia", currency: "Shilling", code: "SOS" },
  { country: "Suriname", currency: "Dollar", code: "SRD" },
  { country: "South Sudan", currency: "Pound", code: "SSP" },
  { country: "São Tomé and Príncipe", currency: "Dobra", code: "STN" },
  { country: "Syria", currency: "Pound", code: "SYP" },
  { country: "Eswatini", currency: "Lilangeni", code: "SZL" },
  { country: "Thailand", currency: "Baht", code: "THB" },
  { country: "Tajikistan", currency: "Somoni", code: "TJS" },
  { country: "Turkmenistan", currency: "Manat", code: "TMT" },
  { country: "Tunisia", currency: "Dinar", code: "TND" },
  { country: "Tonga", currency: "Paʻanga", code: "TOP" },
  { country: "Turkey", currency: "Lira", code: "TRY" },
  { country: "Trinidad and Tobago", currency: "Dollar", code: "TTD" },
  { country: "Tuvalu", currency: "Dollar", code: "TVD" },
  { country: "Taiwan", currency: "Dollar", code: "TWD" },
  { country: "Tanzania", currency: "Shilling", code: "TZS" },
  { country: "Ukraine", currency: "Hryvnia", code: "UAH" },
  { country: "Uganda", currency: "Shilling", code: "UGX" },
  { country: "United States", currency: "Dollar", code: "USD" },
  { country: "Uruguay", currency: "Peso", code: "UYU" },
  { country: "Uzbekistan", currency: "Som", code: "UZS" },
  { country: "Venezuela", currency: "Bolívar", code: "VES" },
  { country: "Vietnam", currency: "Dong", code: "VND" },
  { country: "Vanuatu", currency: "Vatu", code: "VUV" },
  { country: "Samoa", currency: "Tala", code: "WST" },
  { country: "Central African States", currency: "CFA Franc BEAC", code: "XAF" },
  { country: "Eastern Caribbean", currency: "Dollar", code: "XCD" },
  { country: "Caribbean Netherlands", currency: "Guilder", code: "XCG" },
  { country: "International Monetary Fund", currency: "Special Drawing Rights", code: "XDR" },
  { country: "West African States", currency: "CFA Franc BCEAO", code: "XOF" },
  { country: "French Polynesia", currency: "CFP Franc", code: "XPF" },
  { country: "Yemen", currency: "Rial", code: "YER" },
  { country: "South Africa", currency: "Rand", code: "ZAR" },
  { country: "Zambia", currency: "Kwacha", code: "ZMW" },
  { country: "Zimbabwe", currency: "Gold-backed Dollar", code: "ZWG" },
  { country: "Zimbabwe", currency: "Dollar", code: "ZWL" }
];

export default countriesData